### ISSUE TITLE
今天出错了

### ISSUE THREAD

**Issue by 3538532** [Fansirsqi/Task_job#2]
2023-09-08T00:02:09.9708842Z ##[group]Run python task.py
2023-09-08T00:02:09.9709248Z [36;1mpython task.py[0m
2023-09-08T00:02:09.9763191Z shell: /usr/bin/bash -e {0}
2023-09-08T00:02:09.9763545Z env:
2023-09-08T00:02:09.9769758Z   COOKIE_CONFIG: *** 
2023-09-08T00:02:09.9770250Z   SENDKEY: ***
2023-09-08T00:02:09.9770564Z   WX_TOKEN: 
2023-09-08T00:02:09.9770851Z   UIDS: 
2023-09-08T00:02:09.9771216Z   pythonLocation: /opt/hostedtoolcache/Python/3.11.5/x64
2023-09-08T00:02:09.9771711Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib
2023-09-08T00:02:09.9772030Z ##[endgroup]
2023-09-08T00:02:10.1415844Z Traceback (most recent call last):
2023-09-08T00:02:10.1424925Z   File "/home/runner/work/Task_job_52PJ/Task_job_52PJ/task.py", line 176, in <module>
2023-09-08T00:02:10.1426113Z     main()
2023-09-08T00:02:10.1427341Z   File "/home/runner/work/Task_job_52PJ/Task_job_52PJ/task.py", line 154, in main
2023-09-08T00:02:10.1428075Z     COOKIE_CONFIG = eval(os.environ.get("COOKIE_CONFIG"))
2023-09-08T00:02:10.1478504Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-08T00:02:10.1479160Z   File "<string>", line 1
2023-09-08T00:02:10.1490265Z     *** 
2023-09-08T00:02:10.1490638Z                                    ^
2023-09-08T00:02:10.1490988Z SyntaxError: invalid decimal literal
2023-09-08T00:02:10.1636408Z ##[error]Process completed with exit code 1.

**Comment by Fansirsqi** [comment]
周末看看

**Comment by Fansirsqi** [comment]
我自己的仓库好像没问题,看看是不是cookie或者是哪出了问题

**Comment by 3538532** [comment]
> 我自己的仓库好像没问题,看看是不是cookie或者是哪出了问题

cookie重新获取的，其他都没动，按说不该啊。

**Comment by 3538532** [comment]
> 我自己的仓库好像没问题,看看是不是cookie或者是哪出了问题

你的仓库签到也不对了。

**Comment by Fansirsqi** [comment]
嗯，上午我再看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月12日(周二) 上午9:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Fansirsqi/Task_job] 今天出错了 (Issue #2)




  
我自己的仓库好像没问题,看看是不是cookie或者是哪出了问题
  
你的仓库签到也不对了。

**Comment by Fansirsqi** [comment]
> > 我自己的仓库好像没问题，看看是不是cookie或者是哪个生长的问题
> 
> 你的仓库签到也不对了。

我把代码拉下来,在本地是能正常跑的,可能是github actions的网络问题,目前没有好的在线执行方案

**Comment by Fansirsqi** [comment]
> > > 我自己的仓库好像没问题，看看是不是cookie或者是哪个生长的问题
> > 
> > 
> > 你的仓库签到也不对了。
> 
> 我把代码拉下来，在本地是能正常运行的，可能是github actions的网络问题，目前没有好的在线执行方案

```bash
HTTPSConnectionPool(host='www.52pojie.cn', port=443): Max retries exceeded with url: /home.php?mod=task&do=apply&id=2&referer=%2F (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1936222590>, 'Connection to www.52pojie.cn timed out. (connect timeout=None)'))
```
从报错信息来看也是,连接超时了貌似

**Comment by 3538532** [comment]
估计是把github地址拉黑了。
能否改为在青龙里运行？
